name: example
description: flutter_html example app.
publish_to: none
version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter_html:
    git: 
      url: git@github.com:uptech/flutter_html.git
      ref: allow-srcdoc-and-point-packages-to-uptech-repo
  flutter_html_all:
    git: 
      url: git@github.com:uptech/flutter_html.git
      path: packages/flutter_html_all
      ref: allow-srcdoc-and-point-packages-to-uptech-repo
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:

  uses-material-design: true

  assets:
    - assets/html5.png
    - assets/mac.svg