name: flutter_html_all
description: All optional flutter_html widgets, bundled into a single package.
version: 3.0.0-beta.2
homepage: https://github.com/Sub6Resources/flutter_html
publish_to: none # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=2.2.0"

dependencies:
  flutter:
    sdk: flutter
  html: '>=0.15.0 <1.0.0'
  flutter_html: 
    git: 
      url: git@github.com:uptech/flutter_html.git
      ref: allow-srcdoc-and-point-packages-to-uptech-repo
  flutter_html_audio: 
    git: 
      url: git@github.com:uptech/flutter_html.git
      ref: allow-srcdoc-and-point-packages-to-uptech-repo
      path: packages/flutter_html_audio
  flutter_html_iframe: 
    git:
      url: git@github.com:uptech/flutter_html.git
      path: packages/flutter_html_iframe
      ref: allow-srcdoc-and-point-packages-to-uptech-repo
  flutter_html_math: 
    git:
      url: git@github.com:uptech/flutter_html.git
      path: packages/flutter_html_math
      ref: allow-srcdoc-and-point-packages-to-uptech-repo  
  flutter_html_svg: 
    git:
      url: git@github.com:uptech/flutter_html.git
      path: packages/flutter_html_svg
      ref: allow-srcdoc-and-point-packages-to-uptech-repo  
  flutter_html_table: 
    git:
      url: git@github.com:uptech/flutter_html.git
      path: packages/flutter_html_table
      ref: allow-srcdoc-and-point-packages-to-uptech-repo  
  flutter_html_video: 
    git:
      url: git@github.com:uptech/flutter_html.git
      path: packages/flutter_html_video
      ref: allow-srcdoc-and-point-packages-to-uptech-repo

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

funding:
  - https://opencollective.com/flutter_html

topics:
  - html
  - css
  - widgets
  - layout
  - flutter_html
