name: flutter_html_svg
description: This extension package allows the <svg> tag and svg-based img sources to be rendered using the flutter_html package
version: 3.0.0-beta.2
homepage: https://github.com/Sub6Resources/flutter_html
publish_to: none # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=2.2.0"

dependencies:
  flutter:
    sdk: flutter
  html: '>=0.15.0 <1.0.0'
  flutter_html: 
    git: 
      url: git@github.com:uptech/flutter_html.git
      ref: allow-srcdoc  
  flutter_svg: '>=1.0.0 <3.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  meta: ^1.8.0

funding:
  - https://opencollective.com/flutter_html

topics:
  - html
  - css
  - svg
  - images
  - flutter_html
